name: loar
version: '0.7.0'
grade: stable
summary: Local Archive Utility (LOAR)
description: LOAR is a CLI tool to backup non-tracked files and folder structures
base: core22
confinement: strict

adopt-info: loar
compression: lzo
icon: loar-logo.png
type: app
title: LOAR
issues: https://github.com/cavecafe-cc/loar/issues
contact: https://github.com/cavecafe
website: https://github.com/cavecafe-cc/loar
license: GPL-3.0

architectures:
  - build-on: arm64

apps:
  loar:
    command: loar
    environment:
      DOTNET_ROOT: $SNAP/usr/share/dotnet

parts:
  loar-osx-arm64:
    source: https://github.com/cavecafe-cc/loar.git
    source-type: git
    source-branch: main
    plugin: dotnet
    dotnet-build-configuration: Release
    dotnet-self-contained-runtime-identifier: osx-arm64
    override-build: |
      dotnet restore loar.csproj
      dotnet build loar.csproj -c Release
      dotnet publish loar.csproj -c Release -o $SNAPCRAFT_PART_INSTALL/osx-arm64 --self-contained -r osx-arm64
    build-packages:
      - dotnet-sdk-8.0