name: loar
version: '0.7.0'
grade: stable
summary: Local Archive Utility (LOAR)
description: LOAR is a CLI tool to backup non-tracked files and folder structures
base: core24
confinement: strict

adopt-info: loar
compression: lzo
icon: loar-logo.png
type: app
title: LOAR
issues: https://github.com/cavecafe-cc/loar/issues
contact: https://github.com/cavecafe
website: https://github.com/cavecafe-cc/loar
license: GPL-3.0

apps:
  loar:
    command: loar

#platforms:
#  amd64: {}
#  arm64: {}

environment:
  DOTNET_ROOT: $SNAP/usr/share/dotnet

parts:
  loar:
    source: https://github.com/cavecafe-cc/loar.git
    source-type: git
    source-branch: main
    plugin: dotnet
#    build-snaps:
#      - name: dotnet-sdk-8.0
#        channel: 8.0/stable
    build-packages:
      - dotnet-sdk-8.0
    stage-packages:
      - dotnet-runtime-8.0
    override-build: |
      # Initialize .NET SDK
      dotnet restore
      dotnet build --configuration Release
      dotnet publish --configuration Release --output $SNAPCRAFT_PART_INSTALL/