name: loar
version: '0.7.0'
grade: stable
summary: Local Archive Utility (LOAR)
description: LOAR is a CLI tool to backup non-tracked files and folder structures
base: core22
confinement: strict

adopt-info: loar
compression: lzo
icon: loar-logo.png
type: app
title: LOAR
issues: https://github.com/cavecafe-cc/loar/issues
contact: https://github.com/cavecafe
website: https://github.com/cavecafe-cc/loar
license: GPL-3.0

architectures:
  - build-on: amd64
  #- build-on: arm64

apps:
  loar:
    command: loar
    environment:
      DOTNET_ROOT: $SNAP/usr/share/dotnet

parts:
  loar:
    source: https://github.com/cavecafe-cc/loar.git
    source-type: git
    source-branch: main
    plugin: dotnet
    dotnet-build-configuration: Release
    dotnet-self-contained-runtime-identifier: linux-x64
    #dotnet-self-contained-runtime-identifier: osx-arm64
    #dotnet-self-contained-runtime-identifier: win-x64
    #dotnet-self-contained-runtime-identifier: osx-x64
    build-packages:
      - dotnet-sdk-8.0
    stage-packages:
      - libicu70